import "./globals.css";
import styles from "./page.module.css";
import Header from "./components/Header";
import ApolloProviderWrapper from "./components/ApolloProvider";

export const metadata = {
  title: "GraphQL Project Management Tool",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <ApolloProviderWrapper children={children}>
      <html lang="en">
        <body className="">
          <Header />
          <main className="container">{children}</main>
        </body>
      </html>
    </ApolloProviderWrapper>
  );
}
